---
kind: pipeline
type: docker
name: default

steps:
- name: test
  image: rust:1.57
  environment:
    RUST_BACKTRACE: 1
  commands:
  - rustup component add clippy rustfmt
  - cargo fmt --all -- --check
  - cargo clippy -- -D warnings
  - cargo test
  - RUST_TEST_THREADS=1 cargo test

trigger:
  event:
    include:
      - push
      - pull_request
---
hmac: "3578aa331afc59fb761a53431e3886221fae525ada6b31ddcba805d81bb73236"
kind: signature
...
